package routefusion

import (
	"bytes"
	"encoding/json"
	"net/http"

	"github.com/routefusion/routefusion-golang/client"
)

// Auto-generated by internal/cmd/genmethods/generator.go. DO NOT EDIT!

func (r *Routefusion) GetUser() (
	*UserDetails, error) {
	op := client.Operation{
		HTTPMethod: http.MethodGet,
		HTTPPath:   r.baseURL + "/v1/users/me",
	}

	var response *UserDetails

	req, err := r.cl.NewRequest(op, &response, nil)

	if err != nil {
		return nil, err
	}
	if err := req.Send(); err != nil {
		return nil, err
	}

	return response, nil
}

func (r *Routefusion) UpdateUser(user *User) (
	*UpdatedUserDetails, error) {
	op := client.Operation{
		HTTPMethod: http.MethodPut,
		HTTPPath:   r.baseURL + "/v1/users/me",
	}

	var response *UpdatedUserDetails

	bdy, err := json.Marshal(user)
	if err != nil {
		return nil, err
	}
	req, err := r.cl.NewRequest(op, &response, bytes.NewReader(bdy))

	if err != nil {
		return nil, err
	}
	if err := req.Send(); err != nil {
		return nil, err
	}

	return response, nil
}
